# Name of the action
name: Testing

  # Controls when the action will run (on every push across all branches)
on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #the puppeteer job
  puppeteer:
    name: Puppeteer
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Pull origin development
        run: |
            git pull origin ${{ github.ref }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Puppeteer tests
      # can we just do 'npm test source/tests/sampleP.test.js'
        run: npm test -c jest-puppeteer.config.js source/tests/PuppTests.test.js
